- name: Hello World
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Terraform
      cloud.terraform.terraform:
        project_path: '{{ playbook_dir }}/../terraform'
        state: present
        force_init: true
