- name: Hello World
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Terraform
      community.general.terraform:
        project_path: '{{ playbook_dir }}/../terraform'
        state: present
